[package]
name = "remite-options"
version = "0.1.0"
authors = ["Karl Grasegger <51945878+grasegger@users.noreply.github.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.6"

wee_alloc = "0.4"

[dependencies.futures]
version = "0.3"
features = ["std", "thread-pool"]

[dependencies.browser_storage_sync]
path = "../browser-storage-sync"