# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: apt helper action
      uses: ryankurte/action-apt@v0.1.0
      with:
        # apt packages to install
        packages: "npm curl build-essential pkg-config clang"

    # Runs a set of commands using the runners shell
    - run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y -t wasm32-unknown-unknown --profile minimal
        bash -c "source $HOME/.cargo/env && cargo install wasm-pack"
        bash -c "source $HOME/.cargo/env && make"

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.4.1
      with:
        # Filename for archive
        #filename: # default is release.zip
        # Base path for archive files
        path: build # optional, default is .
        # Working directory before zipping
        #directory: # optional, default is .
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        #type: # optional, default is zip
